name: Dispatch Handler Test

on:
  workflow_dispatch:
    inputs:
      prop41:
        description: 'prop41'
        required: false
        default: 'val41'
  repository_dispatch:
    types: [build-zoo-handler]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Notify main controller
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: jvalkeal/atest1
        event-type: build-zoo-handler
        client-payload: '{"build_zoo_handler":{"repo": "jvalkeal/atest2", "action": "build-succeed"}}'

