name: Dispatch Handler Test2

on:
  workflow_dispatch:
    inputs:
      prop41:
        description: 'prop41'
        required: false
        default: 'val41'
  repository_dispatch:
    types: [build-zoo-handler]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Notify main controller
      uses: jvalkeal/build-zoo-handler@gh7-work1
      with:
        dispatch-handler-token: ${{ secrets.REPO_ACCESS_TOKEN }}
        dispatch-handler-owner: jvalkeal
        dispatch-handler-repo: atest1
        dispatch-handler-event-type: build-zoo-handler
        dispatch-handler-client-payload-data: '{"event": "build-succeed", "prop41": "val41"}'

    # - name: Notify main controller
    #   uses: peter-evans/repository-dispatch@v1
    #   with:
    #     token: ${{ secrets.REPO_ACCESS_TOKEN }}
    #     repository: jvalkeal/atest1
    #     event-type: build-zoo-handler
    #     client-payload: '{"build_zoo_handler":{"repo": "jvalkeal/atest4", "action": "build-succeed"}}'

