name: Dispatch Handler Test2

on:
  workflow_dispatch:
    inputs:
      prop31:
        description: 'prop31'
        required: false
        default: 'val31'
  repository_dispatch:
    types: [build-zoo-handler]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Notify main controller
      uses: jvalkeal/build-zoo-handler@gh7-work1
      with:
        dispatch-handler-token: ${{ secrets.REPO_ACCESS_TOKEN }}
        dispatch-handler-owner: jvalkeal
        dispatch-handler-repo: atest1
        dispatch-handler-event-type: build-zoo-handler
        dispatch-handler-client-payload-data: >
          {
            "event": "build-succeed",
            "prop31": "val31",
            "owner": "jvalkeal",
            "repo": "atest3"
          }
