name: Next Dev Version

on:
  workflow_dispatch:
    inputs:
      build-zoo-handler:
        description: 'Build Zoo Handler Payload'
        required: false

jobs:
  build:
    runs-on: self-hosted
    steps:

    # base setup
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: jvalkeal/setup-maven@v1
      with:
        maven-version: 3.6.2
    - uses: jfrog/setup-jfrog-cli@v1
      with:
        version: 1.43.2
      env:
        JF_ARTIFACTORY_LOCAL: ${{ secrets.JF_ARTIFACTORY_SECRET_LOCAL }}
    - name: Configure JFrog Cli
      run: |
        jfrog rt mvnc \
          --server-id-resolve=local \
          --server-id-deploy=local \
          --repo-resolve-releases=libs-release \
          --repo-resolve-snapshots=libs-snapshot \
          --repo-deploy-releases=libs-release \
          --repo-deploy-snapshots=libs-snapshot

    # zoo extract and ensure
    - name: Extract Zoo Context Properties
      uses: jvalkeal/build-zoo-handler@v0.0.4
      with:
        dispatch-handler-extract-context-properties: true
        ensure-env: |
          BUILD_ZOO_HANDLER_atest4_version

    # build
    - name: Switch to Next Dev Version
      run: |
        jfrog rt mvn build-helper:parse-version \
          versions:set \
          -DprocessAllModules=false -DgenerateBackupPoms=false \
          -DnewVersion='${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.nextIncrementalVersion}-SNAPSHOT'
        jfrog rt mvn versions:set-property \
          -DgenerateBackupPoms=false \
          -Dproperty=demo4.version \
          -DnewVersion=$BUILD_ZOO_HANDLER_atest4_version
        jfrog rt mvn -U -B clean install -DskipTests
        echo BUILD_ZOO_HANDLER_atest3_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) >> $GITHUB_ENV

    # zoo commit
    - name: Commit Next Dev Changes
      uses: jvalkeal/build-zoo-handler@v0.0.4
      with:
        commit-changes-branch: master
        commit-changes-message: Next development version

    # zoo success
    - name: Notify Build Success Zoo Handler Controller
      uses: jvalkeal/build-zoo-handler@v0.0.4
      with:
        dispatch-handler-token: ${{ secrets.REPO_ACCESS_TOKEN }}
        dispatch-handler-client-payload-data: >
          {
            "event": "next-dev-version-succeed"
          }

    # zoo failure
    - name: Notify Build Failure Zoo Handler Controller
      if: ${{ failure() }}
      uses: jvalkeal/build-zoo-handler@v0.0.4
      with:
        dispatch-handler-token: ${{ secrets.REPO_ACCESS_TOKEN }}
        dispatch-handler-client-payload-data: >
          {
            "event": "next-dev-version-failed"
          }
