name: Test Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release Version'
        required: true
        default: '0.0.0'
      test1Version:
        description: 'Test1 Version'
        required: true
        default: '0.0.0'
      test2Version:
        description: 'Test1 Version'
        required: true
        default: '0.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: jvalkeal/setup-maven@v1
      maven-version: 3.6.2

    - uses: jfrog/setup-jfrog-cli@v1
      with:
        version: 1.36.0
      env:
        JF_ARTIFACTORY_SPRING: ${{ secrets.JF_ARTIFACTORY_SECRET_SPRING }}
    - name: Configure JFrog Cli
      run: |
        jfrog rt mvnc --server-id-resolve=spring --server-id-deploy=spring --repo-resolve-releases=libs-spring-dataflow-private-release --repo-deploy-snapshots=libs-spring-dataflow-private-snapshot --repo-resolve-snapshots=libs-spring-dataflow-private-snapshot --repo-deploy-releases=libs-spring-dataflow-private-release

