name: Test Workflow Dispatch

on:
  workflow_dispatch:
    branch: [master]
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Echo log level
      run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
    - name: Multiline command
      run: |
        ls \
          gradle \
          src
        ls \
          src \
          gradle
